//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mydata
    {
        public int id { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Myname { get; set; }
        public string yourname { get; set; }
    }
}
