//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string UName { get; set; }
        public byte[] StID { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Profession { get; set; }
        public string Hobbies { get; set; }
        public System.DateTime DOB { get; set; }
        public string Race { get; set; }
    }
}
